---
title: "Codigo-analisis-Navarro-Paya-Carlos-PEC1"
author: "Carlos Navarro Paya"
date: "2025-03-24"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PEC1 Carlos Navarro Paya

### Cargando paquetes

```{r cargando_paquetes, include=FALSE}
library(SummarizedExperiment)
library(reshape2)
library(ggplot2)
library(factoextra)
library(ggrepel)
library(pheatmap)
library(RColorBrewer)
library(MetaboAnalystR)
```

## Carga de datos

```{r carga_datos}
#Cargando los datos desde los .csv
features = read.csv("datos/features.csv", sep=";",row.names=1)
metadata = read.csv("datos/metadata.csv", sep=";",header=TRUE, stringsAsFactors = FALSE)
metabolite_names = read.csv("datos/metaboliteNames.csv", sep=";",header=TRUE,stringsAsFactors = FALSE)
#preparando colData y rowData
rowData = DataFrame(
  metaboliteName = metabolite_names$names,
  PubChem_ID = metabolite_names$PubChem,
  KEGG_ID = metabolite_names$KEGG
)
rownames(rowData) = rownames(features)

colData = DataFrame(metadata)
rownames(colData) = colData$ID

# Generando el objeto SummarizedExperiment
se = SummarizedExperiment(
  assays = list(counts = as.matrix(features)),
  colData = colData,
  rowData = rowData
  
)
se

save(se, file = "summarizedExperiment.rda")
```

## Analisis preliminar

```{r analisis_preliminar}
# Boxplot por muestra
#extrayendo datos de metabolitos a una matriz
datos = assay(se)
#transponiendo matriz y pasando a formato "largo" para ggplot2 (requiere el formato largo)
datos_largo = melt(t(datos))
colnames(datos_largo) = c("Sample","Metabolite","Value")
head(datos_largo)

ggplot(datos_largo, aes(x=Sample, y=Value)) + geom_boxplot(fill = "lightblue", outlier.color= "red") + theme_bw() + labs(title = "Distribucion de valores por muestra", x="Muestra", y="Valor del Metabolito") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggsave("figuras/boxplot-raw.png")

# Boxplot por muestra escala logaritmica
ggplot(datos_largo, aes(x=Sample, y=Value)) + geom_boxplot(fill = "lightblue", outlier.color= "red") + scale_y_log10() + theme_bw() + labs(title = "Distribucion de valores por muestra escalado  log10", x="Muestra", y="Valor del Metabolito") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggsave("figuras/boxplot-log10.png")

# Boxplot por muestra datos escalados con Z-score
datos_escalados_z_largos = melt(t(scale(datos)))
colnames(datos_escalados_z_largos) = c("Sample","Metabolite","Value")
ggplot(datos_escalados_z_largos, aes(x=Sample, y=Value)) + geom_boxplot(fill = "lightblue", outlier.color= "red") + scale_y_log10() + theme_bw() + labs(title = "Distribucion de valores por  muestra escalados (Z-score)", x="Muestra", y="Valor del Metabolito") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggsave("figuras/boxplot-norm.png")
dev.off()
# Conteo de NA por muestra y metabolito
na_por_muestra = colSums((is.na(datos)))
na_por_metabolito = rowSums(is.na(datos))

png("figuras/na-muestras.png")
barplot(na_por_muestra,
        main ="Valores NA por muestra",
        xlab ="Muestra", ylab = "Numero de NA",
        las = 2, col = "lightblue", cex.names = 0.7
  
)
dev.off

png("figuras/na-metabolitos.png")
barplot(na_por_metabolito,
        main ="Valores NA por metabolito",
        xlab ="Metabolito", ylab = "Numero de NA",
        las = 2, col = "lightblue", cex.names = 0.7
  
)
dev.off()

#Eliminando los metabolitos con NA del objeto se
se_trim = se[rowSums(is.na(datos)) < ncol(se),]
dim(se)
dim(se_trim)
#se eliminan 182 metabolitos
```

## Analisis PCA

```{r analisis_PCA}

#cargando los datos sin NA en variable para realizar PCA y haciendo la transformacion de log10
pca_mat = assay(se_trim)
pca_mat_log = log10(pca_mat + 1) #se suma 1 para evitar el log de 0
#transponiendo para usar con PCA
pca_mat_log_t = t(pca_mat_log)
#ejecutando el pca
pca_resultado = prcomp(pca_mat_log_t, scale. = TRUE, center = TRUE)
#extrayendo los primeros 40 componentes principales
pca_40_df = as.data.frame(pca_resultado$x[, 1:40])
#ajustando los nombres de muestra y tratamiento para el plot
pca_40_df$Sample = rownames(pca_40_df)
pca_40_df$Group = colData(se_trim)$Treatment[match(pca_40_df$Sample, rownames(colData(se_trim)))]
#Tabla de componentes primeras 6 entradas
head(pca_40_df)
#Varianza explicada por cada PC (primeras 40 PC)
var_explicada = summary(pca_resultado)$importance[2, 1:40]
Var_acumulada = cumsum(var_explicada)
var_explicada
Var_acumulada

#grafico de Varianza acumulada
png("figuras/pca-codo.png")
plot(Var_acumulada,
     type = "b", pch = 19, xlab = "Numero de componentes principales",
     ylab = "Varianza acumulada explicada",
     main = "Varianza acumulada explicada (PC1 a PC40)")
dev.off()

#grafico PC1 Vs PC2
#seleccionando dos primeros PC
pca_2_df = as.data.frame(pca_resultado$x[, 1:2])
#a単adiendo nombres
pca_2_df$Sample = rownames(pca_2_df)
pca_2_df$Group = colData(se_trim)$Treatment[match(pca_2_df$Sample, rownames(colData(se_trim)))]
#extrayendo varianza para las etiquetas
var_exp_label = summary(pca_resultado)$importance[2, 1:2]*100
#grafico del PC1 Vs PC2
ggplot(pca_2_df, aes(x= PC1, y = PC2, color = Group)) + geom_point(size = 3, alpha = 0.8) + theme_minimal() + labs(
  title = "PC1 Vs PC2",
  x = paste0("PC1 (" ,round(var_exp_label[1], 1), "%var. expl.)"),
  y = paste0("PC2 (" ,round(var_exp_label[2], 1), "%var. expl.)"),
) + scale_color_manual(values=c("Baseline" = "grey", "Apple"="green", "Cranberry"="red")) + theme(plot.title = element_text(hjust = 0.5))
ggsave("figuras/pca-PC1-PC2.png")

#grafico PC1 Vs PC3
#seleccionando dos primeros PC
pca_3_df = as.data.frame(pca_resultado$x[, 1:3])
#a単adiendo nombres
pca_3_df$Sample = rownames(pca_3_df)
pca_3_df$Group = colData(se_trim)$Treatment[match(pca_3_df$Sample, rownames(colData(se_trim)))]
#extrayendo varianza para las etiquetas
var_exp_label = summary(pca_resultado)$importance[2, 1:3]*100
#grafico del PC1 Vs PC2
ggplot(pca_3_df, aes(x= PC1, y = PC3, color = Group)) + geom_point(size = 3, alpha = 0.8) + theme_minimal() + labs(
  title = "PC1 Vs PC3",
  x = paste0("PC1 (" ,round(var_exp_label[1], 1), "%var. expl.)"),
  y = paste0("PC3 (" ,round(var_exp_label[3], 1), "%var. expl.)"),
) + scale_color_manual(values=c("Baseline" = "grey", "Apple"="green", "Cranberry"="red")) + theme(plot.title = element_text(hjust = 0.5))
ggsave("figuras/pca-PC1-PC3.png")

#Analisis de las cargas de cada PC

#Extrayendo los loadings de los resultados del pca para PC1 PC2 y PC3
loadings = pca_resultado$rotation

top_PC1 = sort(abs(loadings[,"PC1"]), decreasing = TRUE)[1:10]
top_PC1_names = names(sort(abs(loadings[,"PC1"]), decreasing = TRUE)[1:10])
metabolitos_PC1 = rowData(se_trim)[top_PC1_names,"metaboliteName"]
top_PC2 = sort(abs(loadings[,"PC2"]), decreasing = TRUE)[1:10]
top_PC2_names = names(sort(abs(loadings[,"PC2"]), decreasing = TRUE)[1:10])
metabolitos_PC2 = rowData(se_trim)[top_PC2_names,"metaboliteName"]
top_PC3 = sort(abs(loadings[,"PC3"]), decreasing = TRUE)[1:10]
top_PC3_names = names(sort(abs(loadings[,"PC3"]), decreasing = TRUE)[1:10])
metabolitos_PC3 = rowData(se_trim)[top_PC3_names,"metaboliteName"]

df_PC1 = data.frame(
  Metabolito=metabolitos_PC1,
  Loading = top_PC1
)
df_PC2 = data.frame(
  Metabolito=metabolitos_PC2,
  Loading = top_PC2
)
df_PC3 = data.frame(
  Metabolito=metabolitos_PC3,
  Loading = top_PC3
)

#datos de los top 10 metabolitos
top_PC1
metabolitos_PC1
metabolitos_PC2
top_PC1
metabolitos_PC3
top_PC1

#graficos de los top 10 metabolitos
ggplot(df_PC1, aes(x=reorder(Metabolito, Loading), y = Loading)) + geom_bar(stat="identity", fill = "lightblue") + coord_flip() + labs(
title="Top 10 metabolitos mas influyentes en PC1",
x="Metabolito",
y="Carga"
) + 
theme_minimal()
ggsave("figuras/cargas-PC1.png")

ggplot(df_PC2, aes(x=reorder(Metabolito, Loading), y = Loading)) + geom_bar(stat="identity", fill = "lightblue") + coord_flip() + labs(
title="Top 10 metabolitos mas influyentes en PC2",
x="Metabolito",
y="Carga"
) + 
theme_minimal()
ggsave("figuras/cargas-PC2.png")

ggplot(df_PC3, aes(x=reorder(Metabolito, Loading), y = Loading)) + geom_bar(stat="identity", fill = "lightblue") + coord_flip() + labs(
title="Top 10 metabolitos mas influyentes en PC3",
x="Metabolito",
y="Carga"
) + 
theme_minimal()
ggsave("figuras/cargas-PC3.png")

#Grafico Biplot de los 10 componentes de cada 
#cambiando de id a nombre de metabolito para las cargas (vectores en el plot)
rownames(pca_resultado$rotation) = metabolite_names[rownames(pca_resultado$rotation)]
#obteniendo los grupos de tratamiento
grupos = factor(colData(se_trim)$Treatment, levels= c("Baseline","Apple","Cranberry"))
grupos
#generando biplots
fviz_pca_biplot(
  pca_resultado,
  geom.ind = "point", #muestras siendo puntos
  col.ind = grupos,  #coloreando puntos por tratamiento
  palette = c("Baseline" = "grey", "Apple"="green", "Cranberry"="red"), #colores para cada grupo
  addEllipses = TRUE, #a単adiendo elipses por grupo
  label = "var",  #variables (metabolitos) como flechas
  select.var = list(contrib = 10), #solo las variables top 10 segun contribucion
  col.var = "blue",  #color de las flechas
  repel = TRUE, #evitando etiquetas superpuestas
  title = "Biplot PC1 y PC2: muestras y metabolitos"
)
ggsave("figuras/biplot-PC1-PC2.png")

fviz_pca_biplot(
  pca_resultado, axes = c(1,3),
  geom.ind = "point", #muestras siendo puntos
  col.ind = grupos,  #coloreando puntos por tratamiento
  palette = c("Baseline" = "grey", "Apple"="green", "Cranberry"="red"), #colores para cada grupo
  addEllipses = TRUE, #a単adiendo elipses por grupo
  label = "var",  #variables (metabolitos) como flechas
  select.var = list(contrib = 10), #solo las variables top 10 segun contribucion
  col.var = "blue",  #color de las flechas
  repel = TRUE, #evitando etiquetas superpuestas
  title = "Biplot PC1 y PC3: muestras y metabolitos"
)
ggsave("figuras/biplot-PC1-PC3.png")

```
## Analisis de agrupamiento

```{r analisis_agrupamiento}
#agrupamiento jerarquico con datos log10 escalados

datos_clust = assay(se_trim)
datos_clust_escalados = t(scale(log10(datos_clust+1))) #escalando por metabolito
matriz_distancia = dist(datos_clust_escalados,method = "euclidean") #distancia euclediana entre muestras
#calculando el clustering y ploteando el dendrograma
png("figuras/clustering.png")
hc = hclust(matriz_distancia, method = "ward.D2")
plot(hc, labels=colnames(datos_clust), main="Derograma de Clustering jerarquico",xlab="Muestras",sub="",cex=0.8)
dev.off()

```

## Analisis diferencial con ANOVA

```{r analisis_diferencial}

#ANOVA
#datos para el analisis diferencial de metabolitos
datos_diferencial = log10(assay(se_trim)+1)
grupos = colData(se_trim)$Treatment

#definiendo la funcional ANOVA para usar con cada metabolito
anova_por_metabolito= function(x) {
  modelo = aov(x~grupos)
  resumen = summary(modelo)
  p_valor = resumen[[1]][["Pr(>F)"]][1]
  return(p_valor)
}
#aplicando funciona ANOVA por metabolito para obtener los p_valores
p_valores = apply(datos_diferencial, 1, anova_por_metabolito)

#ajustando p-valores con FDR de Benjamini-Hechberg
p_valores_ajustados = p.adjust(p_valores, method = "fdr")

# Obteniendo los nombres de los metabolitos y creando tabla de resultados
metabolite_names = rowData(se_trim)$metaboliteName
names(metabolite_names) = rownames(se_trim)

resultados_anova = data.frame(
  metabolito_ID = rownames(datos_diferencial),
  nombre = metabolite_names[rownames(datos_diferencial)],
  p_valor = p_valores,
  p_valor_ajustado = p_valores_ajustados
)

#ordenando por significancia los resultados del anova
resultados_anova = resultados_anova[order(resultados_anova$p_valor_ajustado),]

#seleccionando los top 10 metabolitos mas significativos
top_metabolitos = resultados_anova$metabolito_ID[1:10]

#aplicando comparaciones multiples con Tukey HSD para los top 10 metabolitos
# y creando una tabla con estas comparaciones
tabla_comparaciones = data.frame()

for (id in top_metabolitos) {
  valores = datos_diferencial[id, ]
  modelo = aov(valores ~ grupos)
  tukey = TukeyHSD(modelo)
  resultado = as.data.frame(tukey$grupos)
  resultado$Comparacion = rownames(resultado)
  resultado$Metabolito_ID = id
  resultado$Nombre = metabolite_names[id]
  
  # filtrarando por comparaciones significativas
  resultado_filtrado = resultado[resultado$`p adj` < 0.05, 
                                  c("Metabolito_ID", "Nombre", "Comparacion", "diff", "p adj")]
  
  tabla_comparaciones = rbind(tabla_comparaciones, resultado_filtrado)
}

tabla_comparaciones
write.csv(tabla_comparaciones, file="figuras/anova_tukey.csv", row.names = FALSE)


#VOLCANO Cranberry Vs Baseline
#seleccionando datos con solo Cranberry vs Baseline
datos_volcano = datos_diferencial[, grupos %in% c("Cranberry", "Baseline")]
grupos_volcano = factor(grupos[grupos %in% c("Cranberry", "Baseline")])

#creando funcion para calcular t-test entre Cranberry y Baseline
t_test_por_metabolito = function(x) {
  test = t.test(x ~ grupos_volcano)
  logFC = mean(x[grupos_volcano == "Cranberry"]) - mean(x[grupos_volcano == "Baseline"])
  return(c(logFC = logFC, pvalor = test$p.value))
}

#aplicando funcion a cada metabolito (por fila)
resultados_volcano = t(apply(datos_volcano, 1, t_test_por_metabolito))
resultados_volcano = as.data.frame(resultados_volcano)
resultados_volcano$p_valor_ajustado = p.adjust(resultados_volcano$pvalor, method = "fdr")
resultados_volcano$metabolito = rownames(resultados_volcano)
resultados_volcano$nombre = rowData(se_trim)$metaboliteName[match(resultados_volcano$metabolito, rownames(se_trim))]

#seleccionando los 10 metabolitos con mayor cambio absoluto (|logFC|)
top_10 = resultados_volcano[order(abs(resultados_volcano$logFC), decreasing = TRUE), ][1:10, ]
#generando el plot volcano
ggplot(resultados_volcano, aes(x = logFC, y = -log10(p_valor_ajustado))) +
  geom_point(alpha = 0.6) +
  geom_point(data = top_10, color = "red", size = 2) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "red") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "blue") +
  geom_text_repel(data = top_10,
                  aes(label = nombre),
                  size = 3, max.overlaps = Inf) +
  theme_minimal() +
  labs(
    title = "Grafico Volcano: Cranberry vs Baseline",
    x = "Log10 Fold Change (Cranberry - Baseline)",
    y = "-log10(p-valor ajustado)"
  )
ggsave("figuras/volcano-cran-base.png")

#VOLCANO Cranberry vs Apple
#seleccionando datos con solo Cranberry vs Apple
datos_volcano_2 = datos_diferencial[, grupos %in% c("Cranberry", "Apple")]
grupos_volcano_2 = factor(grupos[grupos %in% c("Cranberry", "Apple")])

#creando funcion para calcular t-test entre Cranberry y Apple
t_test_por_metabolito_2 = function(x) {
  test = t.test(x ~ grupos_volcano_2)
  logFC = mean(x[grupos_volcano_2 == "Cranberry"]) - mean(x[grupos_volcano_2 == "Apple"])
  return(c(logFC = logFC, pvalor = test$p.value))
}

#aplicando funcion a cada metabolito (por fila)
resultados_volcano_2 = t(apply(datos_volcano_2, 1, t_test_por_metabolito_2))
resultados_volcano_2 = as.data.frame(resultados_volcano_2)
resultados_volcano_2$p_valor_ajustado = p.adjust(resultados_volcano_2$pvalor, method = "fdr")
resultados_volcano_2$metabolito = rownames(resultados_volcano_2)
resultados_volcano_2$nombre = rowData(se_trim)$metaboliteName[match(resultados_volcano_2$metabolito, rownames(se_trim))]

#seleccionando los 10 metabolitos con mayor cambio absoluto (|logFC|)
top_10_2 = resultados_volcano_2[order(abs(resultados_volcano_2$logFC), decreasing = TRUE), ][1:10, ]

#generando el plot volcano
ggplot(resultados_volcano_2, aes(x = logFC, y = -log10(p_valor_ajustado))) +
  geom_point(alpha = 0.6) +
  geom_point(data = top_10_2, color = "red", size = 2) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "red") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "blue") +
  geom_text_repel(data = top_10_2,
                  aes(label = nombre),
                  size = 3, max.overlaps = Inf) +
  theme_minimal() +
  labs(
    title = "Grafico Volcano: Cranberry vs Apple",
    x = "Log10 Fold Change (Cranberry - Apple)",
    y = "-log10(p-valor ajustado)"
  )

ggsave("figuras/volcano-cran-apple.png")

#heatmap de top 20 metabolitos mas significativos del ANOVA

#Seleccionando los 20 metabolitos mas significativos por ANOVA
top20_ids = resultados_anova$metabolito_ID[1:20]

#extrayendo los nombres de los metabolitos
nombres_metabolitos = rowData(se_trim)$metaboliteName[match(top20_ids, rownames(se_trim))]

#extrayendo la matriz de niveles de metabolitos (log10 transformada) de estos metabolitos
datos_heatmap = log10(assay(se_trim)[top20_ids, ] + 1)

#estandarizando  por metabolito (filas)
datos_heatmap_z = t(scale(t(datos_heatmap)))

#cambiando los ids de metabolito por los nombres reales
rownames(datos_heatmap_z) = nombres_metabolitos

#creando anotaciones para columnas (muestras)
anotacion_col = data.frame(Tratamiento = colData(se_trim)$Treatment)
rownames(anotacion_col) = colnames(datos_heatmap_z)

#generando el grafico heatmap
pheatmap(
  datos_heatmap_z,
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  annotation_col = anotacion_col,
  color = colorRampPalette(rev(brewer.pal(n = 9, name = "RdBu")))(100),
  scale = "none",
  fontsize_row = 6,
  fontsize_col = 6,
  main = "Heatmap de metabolitos mas significativos (ANOVA)",
  filename = "figuras/heatmap.png"
)
```
## Analisis de enriquecimiento

```{r analisis_enriquecimiento}

```